bitbag_imoje_webhook:
  path: /payment/imoje/webhook
  controller: bitbag.sylius_imoje_plugin.controller.shop.webhook.webhook_controller

bitbag_imoje_localized:
  resource: "@BitBagSyliusImojePlugin/Resources/config/routing/shop_routing_localized.yaml"
  prefix: /{_locale}
  requirements:
    _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

bitbag_one_click:
  path: /payment/oneclick/{orderId}
  methods: [ GET ]
  controller: bitbag.sylius_imoje_plugin.controller.shop.oneclick.one_click_controller
