bitbag_imoje_initialize_payment:
  path: /payment/imoje/initialize_payment/{orderId}/{paymentMethodCode}/{blikCode}
  controller: bitbag.sylius_imoje_plugin.controller.shop.initialize_payment_controller
  defaults: {orderId: null, paymentMethodCode: null, blikCode: null}

bitbag_imoje_redirect:
  path: /payment/imoje/redirect/{status}/{paymentId}
  methods: [GET]
  controller: bitbag.sylius_imoje_plugin.controller.shop.redirect_controller

bitbag_imoje_one_click_redirect:
  path: /payment/imoje/oneclick/redirect/{status}/{paymentId}
  controller: bitbag.sylius_imoje_plugin.controller.shop.oneclick.redirect_one_click_controller
