imports:
  - { resource: config/*.yml }
  - { resource: config/services/*.xml }
  - { resource: "@SyliusImojePlugin/Resources/config/sylius/resources.yaml" }
  - { resource: "@SyliusRefundPlugin/Resources/config/app/config.yml" }

parameters:
  sylius_refund.supported_gateways:
    - offline
    - BitBag_imoje

knp_snappy:
  pdf:
    enabled:    true

