sylius_resource:
  resources:
    bitbag_sylius_ing_plugin.ing_transaction:
      classes:
        model: BitBag\SyliusImojePlugin\Entity\IngTransaction
        repository: BitBag\SyliusImojePlugin\Repository\IngTransaction\IngTransactionRepository
        interface: BitBag\SyliusImojePlugin\Entity\IngTransactionInterface
