sylius_resource:
  resources:
    bitbag_sylius_imoje_plugin.imoje_transaction:
      classes:
        model: BitBag\SyliusImojePlugin\Entity\ImojeTransaction
        repository: BitBag\SyliusImojePlugin\Repository\ImojeTransaction\ImojeTransactionRepository
        interface: BitBag\SyliusImojePlugin\Entity\ImojeTransactionInterface
